[project]
name = "moondream-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipython>=9.3.0",
    "moondream>=0.1.0",
    "requests>=2.32.4",
]
